spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud: # With this configuration, I tell my gateway, please connect with the discovery server which is Eureka server, and locate all the details about the microservices.
    gateway:
#      discovery:
#        locator:
#          enabled: false # to disable the default routing configuration of gateway server because we have created our custom routing.
#          lower-case-service-id: true # Please accept the service name with the completely lowercase.
      httpclient: # Timeout configuration for all the microservices that we have
        connect-timeout: 1000
        response-timeout: 10s # means my gateway server will wait at a maximum of 10 seconds to get a response from the actual microservices
    kubernetes:
      discovery:
        all-namespaces: true
        enabled: true # we tell the Gateway Server please leverage the discovery server available inside the cluster to forward the request to the other microservices like accounts, loans and cards.
    discovery: # By default, there is a health indicator bean is going to be created internally. Without this, there will be a problem. In future, when this issue is resolved, then we can remove this property.
      client:
        health-indicator:
          enabled: false
  data: # Redis related configuration for Redis RateLimiter pattern.
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s
  security: # We need to mention what is the auth server url using which my resouce server (gateway server) can download the certificates during the startup of this resource server application.
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs" # This will download the public certificate of the auth server, and using it, my resource server can validate if a given access token is valid or not.


# This is for refreshing configurations at runtime using refresh actuator path
# To enable the actuator API paths. By default, Actuator is not going to expose all the management related API paths. That's why we need to specifically enable them.
management:
  endpoints:
    web:
      exposure:
        include: "*" # means please enable and expose all management endpoint supported by the Spring Boot Actuator.
  endpoint: # to enable the gateway related endpoints inside the actuator
    gateway:
      enabled: true
  info:
    env:
      enabled: true
  metrics: # We tell the micrometer and prometheus that please group all my metrics related to the gateway server under the application name which is gatewayserver.
    tags:
      application: ${spring.application.name}


# The purpose of why we added these info related information is the same information we can see inside the Eureka dashboard.
info:
  app:
    name: "gatewayserver"
    description: "DekanBANK Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      dekankilic:
        gatewayserver: debug
  pattern: # My own custom pattern for distributed tracing. If I did not write this, OpenTelemetry would use its default pattern. But, I want to use my own pattern.
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10 # Using this property, we are communicating to the circuit breaker pattern on how many requests it has to initially monitor before it tries to change the status from close to open. Please monitor at least 10 requests coming towards my account microservice
      permittedNumberOfCallsInHalfOpenState: 2 # In the half_open state, 2 request will be allowed to request.
      failureRateThreshold: 50 # If at least 50% of the requests are failed, then circuit breaker pattern can move to the open state from the close state.
      waitDurationInOpenState: 10000 # My circuit breaker pattern is going to wait 10s whenever it tries to move the half_open state and allow the partial traffic.