
build:
  version: "3.0"

accounts:
  message: "Welcome to DekanBANK accounts related local APIs"
  contactDetails:
    name: "Dekan KILIÇ - Developer"
    email: "dekan.kilic@gmail.com"
  onCallSupport:
    -(555) 555-1234
    -(555) 523-1345
