# We should also tell Spring Boot Framework when this profile has to be activated
spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to DekanBANK accounts related QA APIs"
  contactDetails:
    name: " Mustafa KILIÇ - QA Lead"
    email: "mustafa.kilic@gmail.com"
  onCallSupport:
    -(555) 265-3765
    -(555) 734-8371

