server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config: # We should tell Spring Boot Framework that we have created two different profiles and these are the names of the yml files. I need to mention .yml files that we have created
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles: # By this way, we can activate a specific profile
    active:
      - "qa"

build:
  version: "3.0"

accounts:
  message: "Welcome to DekanBANK accounts related local APIs"
  contactDetails:
    name: "Dekan KILIÇ - Developer"
    email: "dekan.kilic@gmail.com"
  onCallSupport:
    -(555) 555-1234
    -(555) 523-1345

